language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - npm run build --prod
  - cd ./www
  - docker --version # print the version for logging
  - docker build -t udagram-api --build-arg POSTGRES_USERNAME=${POSTGRES_USERNAME} --build-arg  POSTGRES_PASSWORD=${POSTGRES_PASSWORD} --build-arg POSTGRES_DB=${POSTGRES_DB} --build-arg POSTGRES_HOST=${POSTGRES_HOST} --build-arg AWS_REGION=${AWS_REGION} --build-arg AWS_PROFILE=${AWS_PROFILE} --build-arg AWS_BUCKET=${AWS_BUCKET} --build-arg URL=${URL} --build-arg JWT_SECRET=${JWT_SECRET} --build-arg=ACCESS_KEY_ID=${ACCESS_KEY_ID}  --build-arg=SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY} .
  - docker tag udagram-api dishantbatra92/udagram-api:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dishantbatra92/udagram-api
