FROM node:13

ARG POSTGRES_USERNAME=
ENV POSTGRES_USERNAME=$POSTGRES_USERNAME

ARG POSTGRES_PASSWORD=
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ARG POSTGRES_DB=
ENV POSTGRES_DB=$POSTGRES_DB

ARG POSTGRES_HOST=
ENV POSTGRES_HOST=$POSTGRES_HOST

ARG AWS_REGION=
ENV AWS_REGION=$AWS_REGION

ARG AWS_PROFILE=
ENV AWS_PROFILE=$AWS_PROFILE

ARG AWS_BUCKET=
ENV AWS_BUCKET=$AWS_BUCKET

ARG URL=
ENV URL=$URL

ARG JWT_SECRET=
ENV JWT_SECRET=$JWT_SECRET

# Create app directory
WORKDIR /usr/src/app

# Copy app source
COPY . .

# Install dependencies
RUN npm install

# Bind the port that the image will run on
EXPOSE 8080

# Define the Docker image's behavior at runtime
CMD ["node", "server.js"]
